---
network:
  server_hostname: server.slsknet.org
  server_port: 2416
  listening_port: 61000
  use_upnp: false
  upnp_lease_duration: 0
  timeout:
    peer: 10
    distributed: 120
  reconnect:
    auto: true

credentials:
  username: Khyle999
  password: Test1234
  description: No description

sharing:
  limits:
    upload_slots: 2
  download: H:\pyslsk-downloads
  directories:
    - H:\soulseek-downloads
    - H:\My Music
    - H:\pyslsk-uploads

debug:
  search_for_parent: true
