DEFAULT_LISTENING_HOST: str = '0.0.0.0'
PEER_CONNECT_TIMEOUT: float = 10
SERVER_CONNECT_TIMEOUT: float = 30
PEER_INDIRECT_CONNECT_TIMEOUT: float = 60
PEER_INIT_TIMEOUT: float = 5
DISCONNECT_TIMEOUT: float = 10
TRANSFER_TIMEOUT: float = 180