---
network:
  server_hostname: server.slsknet.org
  server_port: 2416
  listening_port: 61000
  upnp:
    enabled: true
    lease_duration: 0
  timeout:
    peer: 10
    distributed: 120
  reconnect:
    auto: true
  peer:
    obfuscate: false

credentials:
  username: null
  password: null
  info:
    description: null
    picture: null

search:
  wishlist: []

sharing:
  limits:
    upload_slots: 2
    upload_speed_kbps: 0
    download_speed_kbps: 0
  download: null
  index:
    store_interval: 120
  directories: []

chats:
  auto_join: true
  private_room_invites: true
  rooms: []

users:
  friends: []
  blocked: []

debug:
  search_for_parent: true
  user_ip_overrides: {}
