name: Release library

on:
  release:
    types: [ published ]


jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate app token
        id: generate-app-token
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Publish aioslsk to PyPi
        uses: code-specialist/pypi-poetry-publish@v1.2
        with:
          PACKAGE_DIRECTORY: "./src/aioslsk/"
          PYTHON_VERSION: "3.10"
          POETRY_VERSION: "2.2.0"
          POETRY_CORE_VERSION: "2.2.0"
          ACCESS_TOKEN: ${{ steps.generate-app-token.outputs.token }}
          BRANCH: "main"
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
